version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8080"
    restart: always
    networks:
      - postgres_network
    depends_on:
      - db

  db:
    hostname: db
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

networks:
  postgres_network:

volumes:
  postgres_data: